Repository slsdetectorgroup/slsDetectorPackage, pull requests merged in 2025-05, with the labels that each got.

#1202 only reorder bits if some sort of digital readout mode enabled
  slsReceiverSoftware/src/DataProcessor.cpp
Labels: action - Bug, status - Awaiting review

#1207 ctb: fix bug in blackfin read access to firmware registers
  slsDetectorServers/ctbDetectorServer/bin/ctbDetectorServer_developer
  slsDetectorServers/ctbDetectorServer/slsDetectorFunctionList.c
  slsDetectorServers/slsDetectorServer/include/blackfin.h
  slsDetectorServers/slsDetectorServer/include/slsDetectorFunctionList.h
  slsReceiverSoftware/src/DataProcessor.h
  slsReceiverSoftware/src/GeneralData.h
  slsReceiverSoftware/tests/test-ArrangeDataBasedOnBitList.cpp
  slsSupportLib/include/sls/versionAPI.h
Labels: action - Bug, status - resolved

#1214 dev: rewrote end() for StaticVector
  slsSupportLib/include/sls/StaticVector.h
  slsSupportLib/tests/test-StaticVector.cpp
Labels: action - Bug

#1209 Dev/automate version part2
  conda-recipes/main-library/meta.yaml
  slsDetectorServers/compileAllServers.sh
  slsDetectorServers/compileAllServers_noAPIUpdate.sh
  slsDetectorServers/compileEigerServer.sh
  slsDetectorServers/ctbDetectorServer/Makefile
  slsDetectorServers/eigerDetectorServer/Makefile
  slsDetectorServers/gotthard2DetectorServer/Makefile
  slsDetectorServers/jungfrauDetectorServer/Makefile
  slsDetectorServers/moenchDetectorServer/Makefile
  slsDetectorServers/mythen3DetectorServer/Makefile
  slsDetectorServers/xilinx_ctbDetectorServer/Makefile
  slsSupportLib/include/sls/Version.h
  slsSupportLib/include/sls/versionAPI.h
  slsSupportLib/src/Version.cpp
  slsSupportLib/tests/CMakeLists.txt
  slsSupportLib/tests/test-Version.cpp
  updateAPIVersion.py
  updateAPIVersion.sh
  updateClientAPIVersion.py
  updateClientAPIVersion.sh
Labels: action - Enhancement
