Repository slsdetectorgroup/slsDetectorPackage, pull requests merged in 2025-04, with the labels that each got.

#1181 Fixed broken import in typecaster.h
  .github/workflows/cmake.yaml
  python/slsdet/__init__.py
  python/src/duration.cpp
  python/src/typecaster.h
  python/tests/test_DurationWrapper.py
Labels: action - Bug

#1177 Pattern documentation
  docs/CMakeLists.txt
  docs/src/index.rst
  docs/src/pattern.rst
Labels: action - Documentation

#1159 Dev/issue dont reorder digital data
  docs/src/binaryfileformat.rst
  docs/src/masterfileattributes.rst
  pyctbgui/pyctbgui/services/Signals.py
  pyctbgui/pyctbgui/ui/signals.ui
  python/slsdet/detector.py
  python/src/detector.cpp
  slsDetectorServers/ctbDetectorServer/slsDetectorFunctionList.c
  slsDetectorSoftware/generator/autocomplete/bash_autocomplete.sh
  slsDetectorSoftware/generator/autocomplete/zsh_autocomplete.sh
  slsDetectorSoftware/generator/commands.yaml
  slsDetectorSoftware/generator/extended_commands.yaml
  slsDetectorSoftware/include/sls/Detector.h
  slsDetectorSoftware/src/Caller.cpp
  slsDetectorSoftware/src/Caller.h
  slsDetectorSoftware/src/Detector.cpp
  slsDetectorSoftware/src/Module.cpp
  slsDetectorSoftware/src/Module.h
  slsDetectorSoftware/src/inferAction.cpp
  slsDetectorSoftware/src/inferAction.h
  slsDetectorSoftware/tests/Caller/test-Caller-rx.cpp
  slsReceiverSoftware/src/ClientInterface.cpp
  slsReceiverSoftware/src/ClientInterface.h
  slsReceiverSoftware/src/DataProcessor.cpp
  slsReceiverSoftware/src/DataProcessor.h
  slsReceiverSoftware/src/GeneralData.h
  slsReceiverSoftware/src/Implementation.cpp
  slsReceiverSoftware/src/Implementation.h
  slsReceiverSoftware/src/MasterAttributes.cpp
  slsReceiverSoftware/src/MasterAttributes.h
  slsReceiverSoftware/src/receiver_defs.h
  slsReceiverSoftware/tests/CMakeLists.txt
  slsReceiverSoftware/tests/test-ArrangeDataBasedOnBitList.cpp
  slsSupportLib/include/sls/sls_detector_funcs.h
Labels: status - Awaiting review

#1193 Dev/automate version number
  .github/workflows/conda_python.yaml
  conda-recipes/main-library/meta.yaml
  conda-recipes/python-client/meta.yaml
  pyproject.toml
  update_version.py
Labels: status - Awaiting review

#1200 Fix/dbitreorder should only be defined for chip and xilinx
  slsReceiverSoftware/src/DataProcessor.cpp
  slsReceiverSoftware/src/DataProcessor.h
  slsReceiverSoftware/src/GeneralData.h
  slsReceiverSoftware/src/Implementation.cpp
  slsReceiverSoftware/src/Implementation.h
  slsReceiverSoftware/tests/test-ArrangeDataBasedOnBitList.cpp
Labels: action - Bug
